name: ci
on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install ShellCheck from apt (no external action tag needed)
      - name: Install ShellCheck
        if: ${{ hashFiles('cleanzone') != '' }}
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      # Lint: do not fail the build on warnings (|| true)
      - name: ShellCheck (non-blocking)
        if: ${{ hashFiles('cleanzone') != '' }}
        run: shellcheck -S warning -x ./cleanzone || true

      # Robust smoke test with clear assertions and debug output
      - name: Smoke test (debug, robust)
        if: ${{ hashFiles('cleanzone') != '' }}
        shell: bash
        run: |
          set -euo pipefail

          chmod +x ./cleanzone

          # Fresh demo workspace
          rm -rf demo
          mkdir -p demo/dist demo/keep
          touch "demo/a.txt:Zone.Identifier"
          touch "demo/dist/b.txt:Zone.Identifier"

          echo "== Dry-run (recursive) with -- excludes =="
          out=$(cd demo && ../cleanzone -rl -- dist)
          printf '%s\n' "$out"

          echo "== Assertions for dry-run output =="
          # a.txt must be listed (our script prints './...')
          if ! grep -Fq "./a.txt:Zone.Identifier" <<<"$out"; then
            echo "Expected './a.txt:Zone.Identifier' in dry-run output"; exit 1
          fi
          # dist/b.txt must be excluded by '-- dist'
          if grep -Fq "./dist/b.txt:Zone.Identifier" <<<"$out"; then
            echo "Expected dist/ to be excluded by '-- dist'"; exit 1
          fi

          echo "== Delete without prompt (rfy) =="
          (cd demo && ../cleanzone -rfy -- dist)

          echo "== Logging in current directory (demo/cleanzone.log) =="
          if [[ ! -f demo/cleanzone.log ]]; then
            echo "Expected log file demo/cleanzone.log to exist"; ls -la demo; exit 1
          fi

          echo "Smoke test passed."

      - name: Note if script is missing
        if: ${{ hashFiles('cleanzone') == '' }}
        run: echo "No 'cleanzone' file found in repo root; skipping checks."
