name: ci
on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ShellCheck
        if: ${{ hashFiles('cleanzone') != '' }}
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: ShellCheck (non-blocking)
        if: ${{ hashFiles('cleanzone') != '' }}
        run: shellcheck -S warning -x ./cleanzone || true

      - name: Smoke test (simple & robust)
        if: ${{ hashFiles('cleanzone') != '' }}
        shell: bash
        run: |
          set -euo pipefail
          chmod +x ./cleanzone

          # Frischer Workspace
          rm -rf demo
          mkdir -p demo/dist demo/keep
          touch "demo/a.txt:Zone.Identifier"
          touch "demo/dist/b.txt:Zone.Identifier"

          echo "== Dry-run (recursive) =="
          (cd demo && ../cleanzone -rl)

          # Nach Dry-run muss alles noch da sein
          test -e "demo/a.txt:Zone.Identifier"
          test -e "demo/dist/b.txt:Zone.Identifier"

          echo "== Delete (rfy) =="
          (cd demo && ../cleanzone -rfy)

          # Danach muss beides weg sein
          if [ -e "demo/a.txt:Zone.Identifier" ]; then
            echo "Expected a.txt:Zone.Identifier to be deleted"; exit 1
          fi
          if [ -e "demo/dist/b.txt:Zone.Identifier" ]; then
            echo "Expected dist/b.txt:Zone.Identifier to be deleted"; exit 1
          fi

          # Log im aktuellen Verzeichnis (demo/) muss existieren
          if [ ! -f "demo/cleanzone.log" ]; then
            echo "Expected log file demo/cleanzone.log to exist"; ls -la demo; exit 1
          fi

          echo "Smoke test passed."

      - name: Note if script is missing
        if: ${{ hashFiles('cleanzone') == '' }}
        run: echo "No 'cleanzone' file found in repo root; skipping checks."
