name: ci
on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ShellCheck
        if: ${{ hashFiles('cleanzone') != '' }}
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: ShellCheck (non-blocking)
        if: ${{ hashFiles('cleanzone') != '' }}
        run: shellcheck -S warning -x ./cleanzone || true

      - name: Smoke test (assert by filesystem state)
        if: ${{ hashFiles('cleanzone') != '' }}
        shell: bash
        run: |
          set -euo pipefail
          set -x

          chmod +x ./cleanzone

          # Fresh demo workspace
          rm -rf demo
          mkdir -p demo/dist demo/keep
          touch "demo/a.txt:Zone.Identifier"
          touch "demo/dist/b.txt:Zone.Identifier"

          # 1) Dry-run shouldn't change files
          (cd demo && ../cleanzone -rl -- dist)

          test -e "demo/a.txt:Zone.Identifier"
          test -e "demo/dist/b.txt:Zone.Identifier"

          # 2) Delete without prompt, but exclude 'dist'
          (cd demo && ../cleanzone -rfy -- dist)

          # Assert: a.txt:Zone.Identifier was deleted
          if [ -e "demo/a.txt:Zone.Identifier" ]; then
            echo "Expected a.txt:Zone.Identifier to be deleted"; exit 1
          fi

          # Assert: dist/b.txt:Zone.Identifier still exists (was excluded)
          if [ ! -e "demo/dist/b.txt:Zone.Identifier" ]; then
            echo "Expected dist/b.txt:Zone.Identifier to remain (excluded)"; exit 1
          fi

          # Assert: log exists in current directory (demo/)
          if [ ! -f "demo/cleanzone.log" ]; then
            echo "Expected log file demo/cleanzone.log to exist"; ls -la demo; exit 1
          fi

          echo "Smoke test passed."

      - name: Note if script is missing
        if: ${{ hashFiles('cleanzone') == '' }}
        run: echo "No 'cleanzone' file found in repo root; skipping checks."
