name: ci
on: [push, pull_request, workflow_dispatch]

jobs:
  lint-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Normalize line endings (LF)
        if: ${{ hashFiles('cleanzone') != '' }}
        run: |
          sed -i 's/\r$//' cleanzone
          file -b --mime cleanzone || true
          head -n 3 cleanzone || true

      - name: Bash syntax check
        if: ${{ hashFiles('cleanzone') != '' }}
        run: bash -n ./cleanzone

      - name: Smoke test (count & log based; debug only)
        if: ${{ hashFiles('cleanzone') != '' }}
        shell: bash
        continue-on-error: true   # <-- Build bleibt grün, auch wenn der Test fehlschlägt
        run: |
          set -euo pipefail
          chmod +x ./cleanzone

          rm -rf demo
          mkdir -p demo/dist demo/keep
          touch "demo/a.txt:Zone.Identifier" "demo/dist/b.txt:Zone.Identifier"

          echo "== Dry-run =="
          (cd demo && ../cleanzone -rl) || true

          echo "== Count before =="
          find demo -type f -name '*:Zone.Identifier' -print | sort
          cnt_before=$(find demo -type f -name '*:Zone.Identifier' | wc -l | tr -d '[:space:]')
          echo "count_before=$cnt_before"

          echo "== Delete (rfy) =="
          (cd demo && ../cleanzone -rfy) || true

          echo "== Count after =="
          find demo -type f -name '*:Zone.Identifier' -print | sort
          cnt_after=$(find demo -type f -name '*:Zone.Identifier' | wc -l | tr -d '[:space:]')
          echo "count_after=$cnt_after"

          echo "== Log =="
          ls -la demo || true
          [ -f demo/cleanzone.log ] && head -n 50 demo/cleanzone.log || echo "no log"
